name: expense_bee
description: "A premium expense management app with AI-powered insights and beautiful UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # UI & Animations
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animations: ^2.0.11
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  
  # Charts & Graphics
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.11
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.0
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Icons & UI Components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  
  # Date & Time
  table_calendar: ^3.1.2
  
  # Image & File handling
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  
  # Biometrics & Security
  local_auth: ^2.3.0
  
  # Export functionality
  pdf: ^3.11.1
  excel: ^4.0.6
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/lottie/
